version: "3"
services:
  
  auth-db:
    image: postgres:14-alpine
    container_name: auth-db
    command: postgres -c 'max_connections=200'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "50m"

  product-db:
    image: postgres:14-alpine
    container_name: product-db
    command: postgres -c 'max_connections=200'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
    volumes:
      - product-db-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "50m"

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=sales-db
      - MONGODB_PASS=123456
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - sales-db-data:/data/db

  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./auth-api:/app
      - auth-api-node-modules:/app/node_modules

  product-api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      
volumes:
  auth-db-data:
  product-db-data:
  sales-db-data:
  rabbitmq-data:
  auth-api-node-modules:

